// <auto-generated />
namespace Webapiservice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NameColAddition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameColAddition));
        
        string IMigrationMetadata.Id
        {
            get { return "202202081300581_NameColAddition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
